name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    uses: Pranayteja15/terraform-github-actions/.github/workflows/terraform_reusable_workflow.yml@main
    with:
      terraform_directory: "./terraform"
      terraform_version: "1.5.7"
      apply: true  # Set to false if you just want a plan
      destroy: false
